# Generated by Django 5.1.1 on 2024-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bybit', '0003_task_usertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.AddField(
            model_name='usertask',
            name='telegram_user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
