# Generated by Django 5.1.1 on 2024-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bybit', '0004_remove_usertask_user_usertask_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
