# Generated by Django 5.1.1 on 2024-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bybit', '0005_task_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
