# Generated by Django 5.1.1 on 2024-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okx', '0002_userstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='user',
        ),
        migrations.AddField(
            model_name='userstate',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstate',
            name='state',
            field=models.IntegerField(choices=[(1, 'State 1'), (2, 'State 2')], default=1),
        ),
    ]
