# Generated by Django 5.1.1 on 2024-12-06 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('state', models.IntegerField(choices=[(1, 'State 1'), (2, 'State 2')], default=1)),
                ('bybit_status', models.BooleanField(default=False)),
                ('okx_status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
