# Generated by Django 5.1.7 on 2025-03-29 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('exchange', models.CharField(choices=[('bybit', 'Bybit'), ('okx', 'OKX')], max_length=10)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('telegram_id', 'exchange')},
            },
        ),
    ]
