# Generated by Django 5.1.7 on 2025-03-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_status', '0002_exchangeapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapikey',
            name='passphrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
